//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JugueteriaEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbo_DetalleBitacora
    {
        public long IdDetalleBitacora { get; set; }
        public long IdBitacora { get; set; }
        public long IdProducto { get; set; }
        public long Cantidad { get; set; }
        public double PrecioCompra { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Bitacora Bitacora { get; set; }
    }
}
